library(RCurl)
x <- getURL("https://raw.githubusercontent.com/hpzheng/bvparm-metalorganics/master/Fe3N-split-2015-2.8.csv")
fe3n <- read.csv(text = x, header=T)
View(fe3n)
table(fe3n$r0)
plot(d,bv)
plot(fe3n$d,fe3n$bv)
install.packages("sqldf")
library(sqldf)
sqldf('select count(*) from fe3n')
sqldf('select refcode,bvs,count(*) as CN from fe3n group by refcode,bvs')
fe3n_sites <- sqldf('select refcode,bvs,count(*) as CN from fe3n group by refcode,bvs')
fe3n_sites <- sqldf('select refcode,bvs,r0,count(*) as CN from fe3n group by refcode,bvs,r0')
